modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Akita Attribute"
description='''Registers palette-derived molten metal fluids using vanilla lava behavior and animation.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="terrablender"
type="required"
versionRange="[${terrablender_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="mekanism"
type="optional"
versionRange="[10.7,)"
ordering="AFTER"
side="BOTH"
